<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AssemblyName>TranscodeTools</AssemblyName>
    <RootNamespace>TranscodeTools</RootNamespace>
    <Title>Transcode Tools</Title>
    <FileVersion>1,0</FileVersion>
  </PropertyGroup>

</Project>
